# laboratorioai900
laboratorioai900
A atividade apresentou o erro:

Encountered user error while fetching data from Dataset. Error: UserErrorException:
	Message: path can't be empty
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "path can't be empty"
    }
}
